/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LinksRouteImport } from './routes/links'
import { Route as DownloaderRouteImport } from './routes/downloader'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VCodeRouteImport } from './routes/v.$code'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as ApiPublicMediaRouteImport } from './routes/api/public/media'
import { Route as AuthenticatedDownloadsIdRouteImport } from './routes/_authenticated/downloads.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloaderRoute = DownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VCodeRoute = VCodeRouteImport.update({
  id: '/v/$code',
  path: '/v/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDownloadsIdRoute =
  AuthenticatedDownloadsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDownloadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloader': typeof DownloaderRoute
  '/links': typeof LinksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/v/$code': typeof VCodeRoute
  '/downloads/$id': typeof AuthenticatedDownloadsIdRoute
  '/api/public/media': typeof ApiPublicMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloader': typeof DownloaderRoute
  '/links': typeof LinksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/v/$code': typeof VCodeRoute
  '/downloads/$id': typeof AuthenticatedDownloadsIdRoute
  '/api/public/media': typeof ApiPublicMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/downloader': typeof DownloaderRoute
  '/links': typeof LinksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/v/$code': typeof VCodeRoute
  '/_authenticated/downloads/$id': typeof AuthenticatedDownloadsIdRoute
  '/api/public/media': typeof ApiPublicMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/downloader'
    | '/links'
    | '/sitemap.xml'
    | '/collections'
    | '/dashboard'
    | '/downloads'
    | '/favorites'
    | '/settings'
    | '/v/$code'
    | '/downloads/$id'
    | '/api/public/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/downloader'
    | '/links'
    | '/sitemap.xml'
    | '/collections'
    | '/dashboard'
    | '/downloads'
    | '/favorites'
    | '/settings'
    | '/v/$code'
    | '/downloads/$id'
    | '/api/public/media'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/downloader'
    | '/links'
    | '/sitemap.xml'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/downloads'
    | '/_authenticated/favorites'
    | '/_authenticated/settings'
    | '/v/$code'
    | '/_authenticated/downloads/$id'
    | '/api/public/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloaderRoute: typeof DownloaderRoute
  LinksRoute: typeof LinksRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VCodeRoute: typeof VCodeRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloader': {
      id: '/downloader'
      path: '/downloader'
      fullPath: '/downloader'
      preLoaderRoute: typeof DownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$code': {
      id: '/v/$code'
      path: '/v/$code'
      fullPath: '/v/$code'
      preLoaderRoute: typeof VCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/downloads/$id': {
      id: '/_authenticated/downloads/$id'
      path: '/$id'
      fullPath: '/downloads/$id'
      preLoaderRoute: typeof AuthenticatedDownloadsIdRouteImport
      parentRoute: typeof AuthenticatedDownloadsRoute
    }
  }
}

interface AuthenticatedDownloadsRouteChildren {
  AuthenticatedDownloadsIdRoute: typeof AuthenticatedDownloadsIdRoute
}

const AuthenticatedDownloadsRouteChildren: AuthenticatedDownloadsRouteChildren =
  {
    AuthenticatedDownloadsIdRoute: AuthenticatedDownloadsIdRoute,
  }

const AuthenticatedDownloadsRouteWithChildren =
  AuthenticatedDownloadsRoute._addFileChildren(
    AuthenticatedDownloadsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloaderRoute: DownloaderRoute,
  LinksRoute: LinksRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VCodeRoute: VCodeRoute,
  ApiPublicMediaRoute: ApiPublicMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
